## Bit Shifting Operation

In [7]:
a = 39
print("binary of a:", bin(a))
b = bin(a << 2)
print("after 2 logical left shift of a:", b)
c = bin(a >> 3)
print("after 3 logical right shift of a:", c)

binary of a: 0b100111
after 2 logical left shift of a: 0b10011100
after 2 logical left shift of a: 0b100


## Logical Operators in Python

In [56]:
a = 5
b = 7
c = 10
a_bin = bin(a)
b_bin = bin(b)
c_bin = bin(c)
print("binary of a:", a_bin[2:].zfill(8))
print("binary of b:", b_bin[2:].zfill(8))
print("binary of c:", c_bin[2:].zfill(8))
print("=================[AND]===================")
# AND
and_result1 = a & b
and_result2 = b & c
print("a AND b    :", bin(and_result1)[2:].zfill(8))
print("b AND c    :", bin(and_result2)[2:].zfill(8))
print("=================[OR]====================")
# OR
or_result1 = a | b
or_result2 = b | c
print("a OR b     :", bin(or_result1)[2:].zfill(8))
print("b OR c     :", bin(or_result2)[2:].zfill(8))
print("=================[XOR]===================")
# XOR
xor_result1 = a ^ b
xor_result2 = b ^ c
print("a XOR b    :", bin(xor_result1)[2:].zfill(8))
print("b XOR c    :", bin(xor_result2)[2:].zfill(8))
print("=================[NOT]===================")
# XOR
not_result1 = ~a
not_result2 = ~b
not_result3 = ~c
print("NOT a      :", bin(not_result1 & 0b11111111)[2:])
print("NOT b      :", bin(not_result2 & 0b11111111)[2:])
print("NOT c      :", bin(not_result3 & 0b11111111)[2:])

binary of a: 00000101
binary of b: 00000111
binary of c: 00001010
=================[AND]===================
a AND b    : 00000101
b AND c    : 00000010
=================[OR]====================
a OR b     : 00000111
b OR c     : 00001111
=================[XOR]===================
a XOR b    : 00000010
b XOR c    : 00001101
=================[NOT]===================
NOT a      : 11111010
NOT b      : 11111000
NOT c      : 11110101


## Right Shift of Graphics

In [34]:
import sys

write = sys.stdout.write


import numpy as np

HEIGHT = 17
WIDTH = 11

x, y = (0, 0)

img_array = np.zeros((HEIGHT, WIDTH), dtype=np.int32)

for x in range(WIDTH):
    for y in range(HEIGHT):
        if x < 2 or 9 <= x:
            continue
        if x == 2 or x == 8:
            if 1 < y and y < 15:
                img_array[y][x] = 255
        if x == 3 or x == 4:
            img_array[x + (x - 3)][x] = 255
            img_array[x + (x - 3) + 1][x] = 255
        if x == 6 or x == 7:
            img_array[x + (x-2)][x] = 255
            img_array[x + (x-2) + 1][x] = 255
        if x == 5:
            img_array[7][x] = 255
            img_array[8][x] = 255
            img_array[9][x] = 255
            
                
print(img_array)

[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 255   0   0   0   0   0 255   0   0]
 [  0   0 255 255   0   0   0   0 255   0   0]
 [  0   0 255 255   0   0   0   0 255   0   0]
 [  0   0 255   0 255   0   0   0 255   0   0]
 [  0   0 255   0 255   0   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0   0 255   0 255   0   0]
 [  0   0 255   0   0   0 255   0 255   0   0]
 [  0   0 255   0   0   0   0 255 255   0   0]
 [  0   0 255   0   0   0   0 255 255   0   0]
 [  0   0 255   0   0   0   0   0 255   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]
