## Bit Shifting Operation

In [7]:
a = 39
print("binary of a:", bin(a))
b = bin(a << 2)
print("after 2 logical left shift of a:", b)
c = bin(a >> 3)
print("after 3 logical right shift of a:", c)

binary of a: 0b100111
after 2 logical left shift of a: 0b10011100
after 2 logical left shift of a: 0b100


## Logical Operators in Python

In [56]:
a = 5
b = 7
c = 10
a_bin = bin(a)
b_bin = bin(b)
c_bin = bin(c)
print("binary of a:", a_bin[2:].zfill(8))
print("binary of b:", b_bin[2:].zfill(8))
print("binary of c:", c_bin[2:].zfill(8))
print("=================[AND]===================")
# AND
and_result1 = a & b
and_result2 = b & c
print("a AND b    :", bin(and_result1)[2:].zfill(8))
print("b AND c    :", bin(and_result2)[2:].zfill(8))
print("=================[OR]====================")
# OR
or_result1 = a | b
or_result2 = b | c
print("a OR b     :", bin(or_result1)[2:].zfill(8))
print("b OR c     :", bin(or_result2)[2:].zfill(8))
print("=================[XOR]===================")
# XOR
xor_result1 = a ^ b
xor_result2 = b ^ c
print("a XOR b    :", bin(xor_result1)[2:].zfill(8))
print("b XOR c    :", bin(xor_result2)[2:].zfill(8))
print("=================[NOT]===================")
# XOR
not_result1 = ~a
not_result2 = ~b
not_result3 = ~c
print("NOT a      :", bin(not_result1 & 0b11111111)[2:])
print("NOT b      :", bin(not_result2 & 0b11111111)[2:])
print("NOT c      :", bin(not_result3 & 0b11111111)[2:])

binary of a: 00000101
binary of b: 00000111
binary of c: 00001010
=================[AND]===================
a AND b    : 00000101
b AND c    : 00000010
=================[OR]====================
a OR b     : 00000111
b OR c     : 00001111
=================[XOR]===================
a XOR b    : 00000010
b XOR c    : 00001101
=================[NOT]===================
NOT a      : 11111010
NOT b      : 11111000
NOT c      : 11110101


## Right Shift of Graphics

In [34]:
import sys

write = sys.stdout.write


import numpy as np

HEIGHT = 17
WIDTH = 11

x, y = (0, 0)

img_array = np.zeros((HEIGHT, WIDTH), dtype=np.int32)

for x in range(WIDTH):
    for y in range(HEIGHT):
        if x < 2 or 9 <= x:
            continue
        if x == 2 or x == 8:
            if 1 < y and y < 15:
                img_array[y][x] = 255
        if x == 3 or x == 4:
            img_array[x + (x - 3)][x] = 255
            img_array[x + (x - 3) + 1][x] = 255
        if x == 6 or x == 7:
            img_array[x + (x-2)][x] = 255
            img_array[x + (x-2) + 1][x] = 255
        if x == 5:
            img_array[7][x] = 255
            img_array[8][x] = 255
            img_array[9][x] = 255
            
                
print(img_array)

[[  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 255   0   0   0   0   0 255   0   0]
 [  0   0 255 255   0   0   0   0 255   0   0]
 [  0   0 255 255   0   0   0   0 255   0   0]
 [  0   0 255   0 255   0   0   0 255   0   0]
 [  0   0 255   0 255   0   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0 255   0   0 255   0   0]
 [  0   0 255   0   0   0 255   0 255   0   0]
 [  0   0 255   0   0   0 255   0 255   0   0]
 [  0   0 255   0   0   0   0 255 255   0   0]
 [  0   0 255   0   0   0   0 255 255   0   0]
 [  0   0 255   0   0   0   0   0 255   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]]


# 学んだこと

- CPUやメモリーのようなICが持つすべてのピンは、直流電圧0Vか+5Vのいずれかである。つまり、ICのピン1本では、2つの状態しか表せない。よって、コンピューターは数字を2進数で扱う。
- ビット(bit)とは、「断片」すなわち小さな情報という意味。
- 2進数の桁数は、8桁、16桁、32桁、…のように8の倍数とするのが一般的だが、これはコンピューターで取り扱う情報の単位が、8桁の2進数「バイト(byte)」を基本としているから。
- メモリーやディスクには、バイト単位でデータが格納されたり、読み取られたりする。そのため、バイトが情報の基本単位になる。
- データを格納するバイト数より数字が小さいときは、上位桁に0を入れる。
- 32ビットプロセッサでは、情報を入出力するためのピンを32本持っている。すなわち、一度に32桁の2進数の情報を処理できる。
- コンピューターは2進数で与えられた情報を、数値なのか、文字なのか、グラフィックスのパターンなのか区別しない。そのため、情報をどのように処理するかは、プログラマーが指示しなければならない。
- シフト演算には、桁をずらすことで、掛け算や割り算の代用にするという使い方もある。
- コンピューターは引き算を行う際に補数を用いて内部的には足し算として演算を行うが、これが成り立つ理由は、絶対値が等しい正の値と負の値を足したときに、0になるからである。(例)1バイトで表した1の二進数表記「00000001」　－1の二進数表記「11111111」: 00000001 + 11111111 = 00000000
- 正と負を両方取りえるデータ型の場合、扱える数の多さは負の数の方が1つ多いが、これは0は符号ビットで考えると正のグループに属するためである。
- 2進数を右シフトする際に、グラフィックス等のパターンを扱う場合は、先頭の数値を右シフトして動かした分だけ0で補間し(論理右シフト)、数値として演算する場合は、符号ビットの値で補間する(算術右シフト)。
- 左シフトの際は、論理も算術も左に移動した分だけ、後ろを0で補間する。
- データのビットサイズを8桁→16桁等に増やす際に、元のデータの符号ビットの値で上位桁を満たすようにすることを符号拡張という。